version: "3.8"

services:
  catalogdb:
    container_name: catalogdb
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: no
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=discountdb
  identitydb:
    container_name: identitydb
    restart: no
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=fakePassw0r!
  orderdb:
    container_name: orderdb
    restart: no
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=fakePassw0r!
  rabbitmq:
    container_name: rabbitmq
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ:Server=rabbitmq
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb; User=sa; Password=fakePassw0r!"
    ports:
      - "5001:80"
    depends_on:
      - identitydb